name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install hurl
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.2.0/hurl_4.2.0_amd64.deb
          sudo dpkg -i hurl_4.2.0_amd64.deb
      - name: Run integration tests
        run: hurl --test --glob "tests/integration/**/*.hurl"
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Run unit tests
        run: hatch run all:test-cov
